
// NEXUS-ONE Advanced Ray Tracing Shader Code
// Generated by Shader_Wizard Agent

RayPayload payload;
[shader("raygeneration")]
void MainRayGen() {
    float3 origin = WorldRayOrigin();
    float3 direction = WorldRayDirection();
    TraceRay(SceneStructure, RAY_FLAG_NONE, 0xFF, 0, 1, 0, RayRequest, payload);
    
    // Calculate PBR Reflection with DLSS 3.5 denoising logic
    OutputTarget[DispatchRaysIndex().xy] = payload.color * GI_Intensity;
}
