#!/usr/bin/env python3
"""
NEXUS-ONE Code Generator & Learning Module
- Analyzes existing code patterns
- Generates new code based on learned patterns
- Tests and validates generated code
- Learns from execution results
"""
import ast
import json
import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

WORKSPACE = Path.cwd()
DATA_DIR = WORKSPACE / "nexus_data"
LOG_DIR = WORKSPACE / "nexus_logs"
CODE_PATTERNS = DATA_DIR / "code_patterns.json"
GENERATED_CODE_DIR = WORKSPACE / "generated"
LOG_FILE = LOG_DIR / "code_generator.log"








def log(msg: str):
    ts = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    line = f"[{ts}] {msg}\n"
    try:
        LOG_DIR.mkdir(exist_ok=True)
        with LOG_FILE.open('a', encoding='utf-8') as f:
            f.write(line)
    except Exception:
        pass
    print(line.strip())








class CodeGenerator:
    def __init__(self):
        self.patterns = self.load_patterns()
        GENERATED_CODE_DIR.mkdir(exist_ok=True, parents=True)
        log("code_generator_init")

    def load_patterns(self):
        try:
            if CODE_PATTERNS.exists():
                return json.loads(CODE_PATTERNS.read_text(encoding='utf-8'))
        except Exception:
            pass
        return {
            "function_templates": [],
            "class_templates": [],
            "common_imports": [],
            "design_patterns": []
        }

    def save_patterns(self):
        try:
            CODE_PATTERNS.write_text(json.dumps(self.patterns, indent=2), encoding='utf-8')
        except Exception as e:
            log(f"save_patterns_error: {e}")

    def learn_from_file(self, file_path: Path):
        """Analyze Python file and learn patterns"""
        if not file_path.exists() or file_path.suffix != '.py':
            return

        try:
            source = file_path.read_text(encoding='utf-8')
            tree = ast.parse(source)

            # Extract imports
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        imp = alias.name
                        if imp not in self.patterns["common_imports"]:
                            self.patterns["common_imports"].append(imp)
                elif isinstance(node, ast.ImportFrom):
                    if node.module and node.module not in self.patterns["common_imports"]:
                        self.patterns["common_imports"].append(node.module)

                # Extract function signatures
                elif isinstance(node, ast.FunctionDef):
                    func_info = {
                        "name": node.name,
                        "args": [arg.arg for arg in node.args.args],
                        "docstring": ast.get_docstring(node),
                        "learned_from": str(file_path)
                    }
                    # Avoid duplicates
                    if not any(f["name"] == node.name for f in self.patterns["function_templates"]):
                        self.patterns["function_templates"].append(func_info)

                # Extract class structures
                elif isinstance(node, ast.ClassDef):
                    class_info = {
                        "name": node.name,
                        "methods": [m.name for m in node.body if isinstance(m, ast.FunctionDef)],
                        "docstring": ast.get_docstring(node),
                        "learned_from": str(file_path)
                    }
                    if not any(c["name"] == node.name for c in self.patterns["class_templates"]):
                        self.patterns["class_templates"].append(class_info)

            self.save_patterns()
            log(f"learned_from_file file={file_path.name} functions={len(self.patterns['function_templates'])} classes={len(self.patterns['class_templates'])}")
        except Exception as e:
            log(f"learn_from_file_error file={file_path} err={e}")

    def learn_from_workspace(self):
        """Scan workspace and learn from all Python files"""
        py_files = list(WORKSPACE.glob("*.py")) + list(WORKSPACE.glob("**/*.py"))
        learned = 0
        for f in py_files[:50]:  # Limit to 50 files
            if "venv" in str(f) or "node_modules" in str(f):
                continue
            self.learn_from_file(f)
            learned += 1
        log(f"learn_from_workspace files={learned}")
        return learned

    def generate_simple_function(self, func_name: str, description: str = "Auto-generated function") -> str:
        """Generate a simple Python function"""
        template = f'''def {func_name}():
    """
    {description}
    Auto-generated by NEXUS-ONE Code Generator
    """
    # TODO: Implement logic
    pass
'''
        return template

    def generate_class(self, class_name: str, methods: list[str] | None = None) -> str:
        """Generate a Python class"""
        methods = methods or ["__init__", "run"]
        template = f'''class {class_name}:
    """
    Auto-generated class by NEXUS-ONE
    """
    def __init__(self):
        pass
'''
        for method in methods:
            if method != "__init__":
                template += f'''
    def {method}(self):
        """TODO: Implement {method}"""
        pass
'''
        return template

    def generate_script(self, script_name: str, template_type: str = "simple") -> Path:
        """Generate a complete Python script"""
        script_path = GENERATED_CODE_DIR / f"{script_name}.py"

        if template_type == "simple":
            code = f'''#!/usr/bin/env python3
"""
{script_name}
Auto-generated by NEXUS-ONE Code Generator
"""
import sys
from datetime import datetime








def main():
    print(f"{{script_name}} started at {{datetime.now()}}")
    # TODO: Add your logic here
    print("Done")

if __name__ == '__main__':
    main()
'''
        elif template_type == "class":
            code = f'''#!/usr/bin/env python3
"""
{script_name}
Auto-generated by NEXUS-ONE Code Generator
"""
import sys
from datetime import datetime

{self.generate_class(script_name.replace('_', ' ').title().replace(' ', ''), ["process", "run"])}








def main():
    obj = {script_name.replace('_', ' ').title().replace(' ', '')}()
    obj.run()

if __name__ == '__main__':
    main()
'''
        else:
            code = self.generate_simple_function("main", f"{script_name} main function")

        try:
            script_path.write_text(code, encoding='utf-8')
            log(f"generated_script name={script_name} type={template_type} path={script_path}")
            return script_path
        except Exception as e:
            log(f"generate_script_error: {e}")
            return GENERATED_CODE_DIR / "error.py"

    def test_generated_code(self, script_path: Path) -> dict:
        """Test generated code by running it"""
        if not script_path.exists():
            return {"error": "File not found"}

        try:
            result = subprocess.run(
                [sys.executable, str(script_path)],
                capture_output=True,
                text=True,
                timeout=5
            )
            log(f"test_code path={script_path.name} rc={result.returncode}")
            return {
                "returncode": result.returncode,
                "stdout": result.stdout[:1000],
                "stderr": result.stderr[:1000]
            }
        except subprocess.TimeoutExpired:
            return {"error": "Timeout"}
        except Exception as e:
            return {"error": str(e)}








def demo_code_generation():
    """Demo: Learn and generate code"""
    gen = CodeGenerator()

    # Learn from workspace
    gen.learn_from_workspace()

    # Generate sample script
    script = gen.generate_script("nexus_demo_script", "class")
    if script:
        print(f"Generated: {script}")
        result = gen.test_generated_code(script)
        print(f"Test result: {result}")

if __name__ == '__main__':
    demo_code_generation()
