#!/usr/bin/env python3
"""
NEXUS-ONE Game Engine Controller
- Unity CLI automation
- Unreal Engine CLI automation
- Project creation and build
- Script management
"""
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

WORKSPACE = Path.cwd()
DATA_DIR = WORKSPACE / "nexus_data"
LOG_DIR = WORKSPACE / "nexus_logs"
GAME_PROJECTS_DIR = WORKSPACE / "game_projects"
LOG_FILE = LOG_DIR / "game_engine.log"






















def log(msg: str):
    ts = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    line = f"[{ts}] {msg}\n"
    try:
        LOG_DIR.mkdir(exist_ok=True)
        with LOG_FILE.open('a', encoding='utf-8') as f:
            f.write(line)
    except Exception:
        pass
    print(line.strip())






















class GameEngineController:
    def __init__(self):
        self.unity_path = self.find_unity()
        self.unreal_path = self.find_unreal()
        GAME_PROJECTS_DIR.mkdir(exist_ok=True, parents=True)
        log("game_engine_controller_init")

    def find_unity(self) -> Path | None:
        """Find Unity installation"""
        possible_paths = [
            Path("C:/Program Files/Unity/Hub/Editor"),
            Path(os.environ.get('ProgramFiles', 'C:/Program Files')) / "Unity" / "Hub" / "Editor"
        ]
        for base in possible_paths:
            if base.exists():
                # Find latest version
                versions = list(base.glob("*/Editor/Unity.exe"))
                if versions:
                    log(f"unity_found path={versions[0]}")
                    return versions[0]
        log("unity_not_found")
        return None

    def find_unreal(self) -> Path | None:
        """Find Unreal Engine installation"""
        possible_paths = [
            Path("C:/Program Files/Epic Games/UE_5.3/Engine/Binaries/Win64/UnrealEditor.exe"),
            Path("C:/Program Files/Epic Games/UE_5.2/Engine/Binaries/Win64/UnrealEditor.exe"),
        ]
        for p in possible_paths:
            if p.exists():
                log(f"unreal_found path={p}")
                return p
        log("unreal_not_found")
        return None

    def create_unity_project(self, project_name: str, template: str = "3D") -> dict:
        """Create new Unity project"""
        if not self.unity_path:
            return {"error": "Unity not found"}

        project_path = GAME_PROJECTS_DIR / f"Unity_{project_name}"
        if project_path.exists():
            return {"error": "Project already exists", "path": str(project_path)}

        try:
            cmd = [
                str(self.unity_path),
                "-quit",
                "-batchmode",
                "-createProject", str(project_path),
                "-logFile", str(LOG_DIR / f"unity_create_{project_name}.log")
            ]

            log(f"unity_create_project name={project_name} template={template}")
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)

            if result.returncode == 0 or project_path.exists():
                log(f"unity_project_created path={project_path}")
                return {"success": True, "path": str(project_path)}
            else:
                return {"error": "Creation failed", "stderr": result.stderr[:500]}
        except subprocess.TimeoutExpired:
            return {"error": "Timeout"}
        except Exception as e:
            log(f"unity_create_error: {e}")
            return {"error": str(e)}

    def create_unity_script(self, project_name: str, script_name: str, script_type: str = "MonoBehaviour") -> dict:
        """Create C# script in Unity project"""
        project_path = GAME_PROJECTS_DIR / f"Unity_{project_name}"
        if not project_path.exists():
            return {"error": "Project not found"}

        scripts_dir = project_path / "Assets" / "Scripts"
        scripts_dir.mkdir(exist_ok=True, parents=True)

        script_file = scripts_dir / f"{script_name}.cs"

        if script_type == "MonoBehaviour":
            code = f'''using UnityEngine;

public class {script_name} : MonoBehaviour
{{
    // Start is called before the first frame update
    void Start()
    {{
        Debug.Log("{script_name} started");
    }}

    // Update is called once per frame
    void Update()
    {{
        // TODO: Add your logic here
    }}
}}
'''
        else:
            code = f'''using UnityEngine;

public class {script_name}
{{
    // Auto-generated by NEXUS-ONE
    public void Run()
    {{
        Debug.Log("{script_name} running");
    }}
}}
'''

        try:
            script_file.write_text(code, encoding='utf-8')
            log(f"unity_script_created script={script_name} project={project_name}")
            return {"success": True, "path": str(script_file)}
        except Exception as e:
            return {"error": str(e)}

    def open_unity_project(self, project_name: str) -> dict:
        """Open Unity project in editor"""
        if not self.unity_path:
            return {"error": "Unity not found"}

        project_path = GAME_PROJECTS_DIR / f"Unity_{project_name}"
        if not project_path.exists():
            return {"error": "Project not found"}

        try:
            cmd = [str(self.unity_path), "-projectPath", str(project_path)]
            subprocess.Popen(cmd)
            log(f"unity_project_opened project={project_name}")
            return {"success": True, "project": project_name}
        except Exception as e:
            return {"error": str(e)}

    def create_unreal_project(self, project_name: str) -> dict:
        """Create new Unreal Engine project (requires UE installed)"""
        if not self.unreal_path:
            return {"error": "Unreal Engine not found"}

        project_path = GAME_PROJECTS_DIR / f"Unreal_{project_name}"
        if project_path.exists():
            return {"error": "Project already exists"}

        try:
            # Note: Unreal project creation typically requires UE's project wizard or CLI tools
            # This is a simplified placeholder
            project_path.mkdir(exist_ok=True, parents=True)
            log(f"unreal_project_placeholder created={project_name}")
            return {
                "success": True,
                "path": str(project_path),
                "note": "Use Unreal Editor to fully initialize project"
            }
        except Exception as e:
            return {"error": str(e)}






















def demo_game_engine():
    """Demo: Create Unity project and script"""
    controller = GameEngineController()

    if controller.unity_path:
        print("Unity found, creating demo project...")
        result = controller.create_unity_project("NexusDemo", "3D")
        print(f"Project creation: {result}")

        if result.get("success"):
            script_result = controller.create_unity_script("NexusDemo", "PlayerController", "MonoBehaviour")
            print(f"Script creation: {script_result}")
    else:
        print("Unity not found. Install Unity Hub and Unity Editor.")

if __name__ == '__main__':
    demo_game_engine()
